CREATE TABLE UTILISATEUR (
  ID_UTILISATEUR BIGINT NOT NULL,
  NOM VARCHAR(50) NOT NULL,
  PRENOM VARCHAR(50) NOT NULL,
  PSEUDO VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  CONSTRAINT pk_utilisateur PRIMARY KEY(ID_UTILISATEUR)
);

CREATE TABLE STATUT (
  ID_STATUT INTEGER NOT NULL,
  STATUT VARCHAR(50) NOT NULL
  CONSTRAINT pk_statut PRIMARY KEY(ID_STATUT)
);


CREATE TABLE DICTIONNAIRE (
  MOT_FR VARCHAR(100) NOT NULL,
  MOT_NGZ VARCHAR(100) NOT NULL DEFAULT 'shingazidja',
  MOT_NDZ VARCHAR(100) NULL DEFAULT 'shindzuwani',
  MOT_MWA VARCHAR(100) NULL DEFAULT 'shimwali',
  MOT_MAO VARCHAR(100) NULL DEFAULT 'shimaore',
  MOT_ANG VARCHAR(100) NULL,
  ID_UTILISATEUR BIGINT NOT NULL DEFAULT '1',
  ID_STATUT INTEGER NOT NULL,
  SUGGESTION VARCHAR(100) NULL,
  DEFINITION_FR VARCHAR(1000) NULL,
  DEFINITION_COM VARCHAR(1000) NULL,
  CONSTRAINT pk_dictionnaire PRIMARY KEY(MOT_FR, MOT_COM),
  CONSTRAINT fk_utilisateur FOREIGN KEY (id_utilisateur) 
  REFERENCES public.utilisateurs (id_utilisateur) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_utilisateur FOREIGN KEY (id_utilisateur) 
  REFERENCES public.utilisateurs (id_utilisateur) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT);

ALTER TABLE public.DICTIONNAIRE; 
CREATE INDEX DICTIONNAIRE_FKIndex1 on DICTIONNAIRE using btree (ID_UTILISATEUR); 
CREATE INDEX DICTIONNAIRE_FKIndex2 on DICTIONNAIRE using btree (ID_STATUT); 


CREATE TABLE ROLE (
  ID INTEGER NOT NULL,
  NOM_ROLE VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE UTILISATEUR_has_ROLE (
  ID_UTILISATEUR BIGINT NOT NULL,
  ID_ROLE INTEGER NOT NULL,
  CONSTRAINT pk_utilisateur_has_role PRIMARY KEY(ID_UTILISATEUR, ID_ROLE));

ALTER TABLE public.utilisateur_hasRole
CREATE INDEX UTILISATEUR_has_ROLE_FKIndex1 on UTILISATEUR_has_ROLE using btree (ID_UTILISATEUR); 
CREATE INDEX UTILISATEUR_has_ROLE_FKIndex2 on UTILISATEUR_has_ROLE using btree (ID_ROLE);