INSERT INTO pays (code, nom) VALUES('AFG','Afghanistan'); 
INSERT INTO pays (code, nom) VALUES('ZAF','Afrique du Sud'); 
INSERT INTO pays (code, nom) VALUES('ALB','Albanie'); 
INSERT INTO pays (code, nom) VALUES('DZA','Algérie'); 
INSERT INTO pays (code, nom) VALUES('DEU','Allemagne'); 
INSERT INTO pays (code, nom) VALUES('AND','Andorre'); 
INSERT INTO pays (code, nom) VALUES('AGO','Angola'); 
INSERT INTO pays (code, nom) VALUES('AIA','Anguilla'); 
INSERT INTO pays (code, nom) VALUES('ATA','Antarctique'); 
INSERT INTO pays (code, nom) VALUES('ATG','Antigua-et-Barbuda'); 
INSERT INTO pays (code, nom) VALUES('SAU','Arabie Saoudite'); 
INSERT INTO pays (code, nom) VALUES('ARG','Argentine'); 
INSERT INTO pays (code, nom) VALUES('ARM','Arménie'); 
INSERT INTO pays (code, nom) VALUES('ABW','Aruba'); 
INSERT INTO pays (code, nom) VALUES('AUS','Australie'); 
INSERT INTO pays (code, nom) VALUES('AUT','Autriche'); 
INSERT INTO pays (code, nom) VALUES('AZE','Azerbaïdjan'); 
INSERT INTO pays (code, nom) VALUES('BHS','Bahamas'); 
INSERT INTO pays (code, nom) VALUES('BHR','Bahreïn'); 
INSERT INTO pays (code, nom) VALUES('BGD','Bangladesh'); 
INSERT INTO pays (code, nom) VALUES('BRB','Barbade'); 
INSERT INTO pays (code, nom) VALUES('BEL','Belgique'); 
INSERT INTO pays (code, nom) VALUES('BLZ','Belize'); 
INSERT INTO pays (code, nom) VALUES('BEN','Bénin'); 
INSERT INTO pays (code, nom) VALUES('BMU','Bermudes'); 
INSERT INTO pays (code, nom) VALUES('BTN','Bhoutan'); 
INSERT INTO pays (code, nom) VALUES('BLR','Biélorussie'); 
INSERT INTO pays (code, nom) VALUES('BOL','Bolivie'); 
INSERT INTO pays (code, nom) VALUES('BIH','Bosnie-Herzégovine'); 
INSERT INTO pays (code, nom) VALUES('BWA','Botswana'); 
INSERT INTO pays (code, nom) VALUES('BRA','Brésil'); 
INSERT INTO pays (code, nom) VALUES('VGB','British Virgin Islands'); 
INSERT INTO pays (code, nom) VALUES('BRN','Brunei Darussalam'); 
INSERT INTO pays (code, nom) VALUES('BGR','Bulgarie'); 
INSERT INTO pays (code, nom) VALUES('BFA','Burkina Faso'); 
INSERT INTO pays (code, nom) VALUES('BDI','Burundi'); 
INSERT INTO pays (code, nom) VALUES('KHM','Cambodge'); 
INSERT INTO pays (code, nom) VALUES('CMR','Cameroun'); 
INSERT INTO pays (code, nom) VALUES('CAN','Canada'); 
INSERT INTO pays (code, nom) VALUES('CPV','Cap-Vert'); 
INSERT INTO pays (code, nom) VALUES('CHL','Chili'); 
INSERT INTO pays (code, nom) VALUES('CHN','Chine'); 
INSERT INTO pays (code, nom) VALUES('CYP','Chypre'); 
INSERT INTO pays (code, nom) VALUES('COL','Colombie'); 
INSERT INTO pays (code, nom) VALUES('COM','Comores'); 
INSERT INTO pays (code, nom) VALUES('PRK','Corée du Nord'); 
INSERT INTO pays (code, nom) VALUES('KOR','Corée du Sud'); 
INSERT INTO pays (code, nom) VALUES('CRI','Costa Rica'); 
INSERT INTO pays (code, nom) VALUES('CIV','Côte d’Ivoire'); 
INSERT INTO pays (code, nom) VALUES('HRV','Croatie'); 
INSERT INTO pays (code, nom) VALUES('CUB','Cuba'); 
INSERT INTO pays (code, nom) VALUES('DNK','Danemark'); 
INSERT INTO pays (code, nom) VALUES('DJI','Djibouti'); 
INSERT INTO pays (code, nom) VALUES('DMA','Dominique'); 
INSERT INTO pays (code, nom) VALUES('EGY','Égypte'); 
INSERT INTO pays (code, nom) VALUES('ARE','Émirats Arabes Unis'); 
INSERT INTO pays (code, nom) VALUES('ECU','Équateur'); 
INSERT INTO pays (code, nom) VALUES('ERI','Érythrée'); 
INSERT INTO pays (code, nom) VALUES('ESP','Espagne'); 
INSERT INTO pays (code, nom) VALUES('EST','Estonie'); 
INSERT INTO pays (code, nom) VALUES('USA','États-Unis'); 
INSERT INTO pays (code, nom) VALUES('ETH','Éthiopie'); 
INSERT INTO pays (code, nom) VALUES('FJI','Fidji'); 
INSERT INTO pays (code, nom) VALUES('FIN','Finlande'); 
INSERT INTO pays (code, nom) VALUES('FRA','France'); 
INSERT INTO pays (code, nom) VALUES('GAB','Gabon'); 
INSERT INTO pays (code, nom) VALUES('GMB','Gambie'); 
INSERT INTO pays (code, nom) VALUES('GEO','Géorgie'); 
INSERT INTO pays (code, nom) VALUES('SGS','Géorgie du Sud et les îles Sandwich du Sud'); 
INSERT INTO pays (code, nom) VALUES('GHA','Ghana'); 
INSERT INTO pays (code, nom) VALUES('GIB','Gibraltar'); 
INSERT INTO pays (code, nom) VALUES('GRC','Grèce'); 
INSERT INTO pays (code, nom) VALUES('GRD','Grenade'); 
INSERT INTO pays (code, nom) VALUES('GRL','Groenland'); 
INSERT INTO pays (code, nom) VALUES('GLP','Guadeloupe'); 
INSERT INTO pays (code, nom) VALUES('GUM','Guam'); 
INSERT INTO pays (code, nom) VALUES('GTM','Guatemala'); 
INSERT INTO pays (code, nom) VALUES('GGY','Guernesey'); 
INSERT INTO pays (code, nom) VALUES('GIN','Guinée'); 
INSERT INTO pays (code, nom) VALUES('GNQ','Guinée équatoriale'); 
INSERT INTO pays (code, nom) VALUES('GNB','Guinée-Bissau'); 
INSERT INTO pays (code, nom) VALUES('GUY','Guyane'); 
INSERT INTO pays (code, nom) VALUES('GUF','Guyane française'); 
INSERT INTO pays (code, nom) VALUES('HTI','Haïti'); 
INSERT INTO pays (code, nom) VALUES('HND','Honduras'); 
INSERT INTO pays (code, nom) VALUES('HKG','Hong Kong'); 
INSERT INTO pays (code, nom) VALUES('HUN','Hongrie'); 
INSERT INTO pays (code, nom) VALUES('BVT','Île Bouvet'); 
INSERT INTO pays (code, nom) VALUES('CXR','Île Christmas'); 
INSERT INTO pays (code, nom) VALUES('IMN','Ile de Man'); 
INSERT INTO pays (code, nom) VALUES('NFK','Île Norfolk'); 
INSERT INTO pays (code, nom) VALUES('ALA','Îles Åland'); 
INSERT INTO pays (code, nom) VALUES('CYM','Iles Cayman'); 
INSERT INTO pays (code, nom) VALUES('CCK','Îles Cocos'); 
INSERT INTO pays (code, nom) VALUES('COK','Îles Cook'); 
INSERT INTO pays (code, nom) VALUES('FLK','Îles Falkland'); 
INSERT INTO pays (code, nom) VALUES('FRO','Îles Féroé'); 
INSERT INTO pays (code, nom) VALUES('HMD','Îles Heard-et-MacDonald'); 
INSERT INTO pays (code, nom) VALUES('MNP','Îles Mariannes du Nord'); 
INSERT INTO pays (code, nom) VALUES('MHL','Îles Marshall'); 
INSERT INTO pays (code, nom) VALUES('UMI','Îles mineures éloignées des États-Unis'); 
INSERT INTO pays (code, nom) VALUES('SLB','Îles Salomon'); 
INSERT INTO pays (code, nom) VALUES('TCA','Îles Turques-et-Caïques'); 
INSERT INTO pays (code, nom) VALUES('VIR','Îles Vierges américaines'); 
INSERT INTO pays (code, nom) VALUES('IND','Inde'); 
INSERT INTO pays (code, nom) VALUES('IDN','Indonésie'); 
INSERT INTO pays (code, nom) VALUES('IRQ','Irak'); 
INSERT INTO pays (code, nom) VALUES('IRN','Iran'); 
INSERT INTO pays (code, nom) VALUES('IRL','Irlande'); 
INSERT INTO pays (code, nom) VALUES('ISL','Islande'); 
INSERT INTO pays (code, nom) VALUES('ISR','Israël'); 
INSERT INTO pays (code, nom) VALUES('ITA','Italie'); 
INSERT INTO pays (code, nom) VALUES('JAM','Jamaïque'); 
INSERT INTO pays (code, nom) VALUES('JPN','Japon'); 
INSERT INTO pays (code, nom) VALUES('JEY','Jersey'); 
INSERT INTO pays (code, nom) VALUES('JOR','Jordanie'); 
INSERT INTO pays (code, nom) VALUES('KAZ','Kazakhstan'); 
INSERT INTO pays (code, nom) VALUES('KEN','Kenya'); 
INSERT INTO pays (code, nom) VALUES('KGZ','Kirghizistan'); 
INSERT INTO pays (code, nom) VALUES('KIR','Kiribati'); 
INSERT INTO pays (code, nom) VALUES('KWT','Koweït'); 
INSERT INTO pays (code, nom) VALUES('LAO','Laos'); 
INSERT INTO pays (code, nom) VALUES('LSO','Lesotho'); 
INSERT INTO pays (code, nom) VALUES('LVA','Lettonie'); 
INSERT INTO pays (code, nom) VALUES('LBN','Liban'); 
INSERT INTO pays (code, nom) VALUES('LBR','Libéria'); 
INSERT INTO pays (code, nom) VALUES('LBY','Libye'); 
INSERT INTO pays (code, nom) VALUES('LIE','Liechtenstein'); 
INSERT INTO pays (code, nom) VALUES('LTU','Lituanie'); 
INSERT INTO pays (code, nom) VALUES('LUX','Luxembourg'); 
INSERT INTO pays (code, nom) VALUES('MAC','Macao'); 
INSERT INTO pays (code, nom) VALUES('MKD','Macédoine'); 
INSERT INTO pays (code, nom) VALUES('MDG','Madagascar'); 
INSERT INTO pays (code, nom) VALUES('MYS','Malaisie'); 
INSERT INTO pays (code, nom) VALUES('MWI','Malawi'); 
INSERT INTO pays (code, nom) VALUES('MDV','Maldives'); 
INSERT INTO pays (code, nom) VALUES('MLI','Mali'); 
INSERT INTO pays (code, nom) VALUES('MLT','Malte'); 
INSERT INTO pays (code, nom) VALUES('MAR','Maroc'); 
INSERT INTO pays (code, nom) VALUES('MTQ','Martinique'); 
INSERT INTO pays (code, nom) VALUES('MUS','Maurice'); 
INSERT INTO pays (code, nom) VALUES('MRT','Mauritanie'); 
INSERT INTO pays (code, nom) VALUES('MYT','Mayotte'); 
INSERT INTO pays (code, nom) VALUES('MEX','Mexique'); 
INSERT INTO pays (code, nom) VALUES('FSM','Micronésie'); 
INSERT INTO pays (code, nom) VALUES('MDA','Moldavie'); 
INSERT INTO pays (code, nom) VALUES('MCO','Monaco'); 
INSERT INTO pays (code, nom) VALUES('MNG','Mongolie'); 
INSERT INTO pays (code, nom) VALUES('MNE','Monténégro'); 
INSERT INTO pays (code, nom) VALUES('MSR','Montserrat'); 
INSERT INTO pays (code, nom) VALUES('MOZ','Mozambique'); 
INSERT INTO pays (code, nom) VALUES('MMR','Myanmar'); 
INSERT INTO pays (code, nom) VALUES('NAM','Namibie'); 
INSERT INTO pays (code, nom) VALUES('NRU','Nauru'); 
INSERT INTO pays (code, nom) VALUES('NPL','Népal'); 
INSERT INTO pays (code, nom) VALUES('NIC','Nicaragua'); 
INSERT INTO pays (code, nom) VALUES('NER','Niger'); 
INSERT INTO pays (code, nom) VALUES('NGA','Nigeria'); 
INSERT INTO pays (code, nom) VALUES('NIU','Niue'); 
INSERT INTO pays (code, nom) VALUES('NOR','Norvège'); 
INSERT INTO pays (code, nom) VALUES('NCL','Nouvelle-Calédonie'); 
INSERT INTO pays (code, nom) VALUES('NZL','Nouvelle-Zélande'); 
INSERT INTO pays (code, nom) VALUES('OMN','Oman'); 
INSERT INTO pays (code, nom) VALUES('UGA','Ouganda'); 
INSERT INTO pays (code, nom) VALUES('UZB','Ouzbékistan'); 
INSERT INTO pays (code, nom) VALUES('PAK','Pakistan'); 
INSERT INTO pays (code, nom) VALUES('PLW','Palau'); 
INSERT INTO pays (code, nom) VALUES('PSE','Palestine'); 
INSERT INTO pays (code, nom) VALUES('PAN','Panama'); 
INSERT INTO pays (code, nom) VALUES('PNG','Papouasie-Nouvelle-Guinée'); 
INSERT INTO pays (code, nom) VALUES('PRY','Paraguay'); 
INSERT INTO pays (code, nom) VALUES('NLD','Pays-Bas'); 
INSERT INTO pays (code, nom) VALUES('PER','Pérou'); 
INSERT INTO pays (code, nom) VALUES('PHL','Philippines'); 
INSERT INTO pays (code, nom) VALUES('PCN','Pitcairn'); 
INSERT INTO pays (code, nom) VALUES('POL','Pologne'); 
INSERT INTO pays (code, nom) VALUES('PYF','Polynésie française'); 
INSERT INTO pays (code, nom) VALUES('PRT','Portugal'); 
INSERT INTO pays (code, nom) VALUES('PRI','Puerto Rico'); 
INSERT INTO pays (code, nom) VALUES('QAT','Qatar'); 
INSERT INTO pays (code, nom) VALUES('CAF','République centrafricaine'); 
INSERT INTO pays (code, nom) VALUES('COD','République démocratique du Congo'); 
INSERT INTO pays (code, nom) VALUES('DOM','République dominicaine'); 
INSERT INTO pays (code, nom) VALUES('COG','République du Congo'); 
INSERT INTO pays (code, nom) VALUES('CZE','République tchèque'); 
INSERT INTO pays (code, nom) VALUES('REU','Réunion'); 
INSERT INTO pays (code, nom) VALUES('ROU','Roumanie'); 
INSERT INTO pays (code, nom) VALUES('GBR','Royaume-Uni'); 
INSERT INTO pays (code, nom) VALUES('RUS','Russie'); 
INSERT INTO pays (code, nom) VALUES('RWA','Rwanda'); 
INSERT INTO pays (code, nom) VALUES('ESH','Sahara occidental'); 
INSERT INTO pays (code, nom) VALUES('BLM','Saint-Barthélemy'); 
INSERT INTO pays (code, nom) VALUES('SHN','Sainte-Hélène'); 
INSERT INTO pays (code, nom) VALUES('LCA','Sainte-Lucie'); 
INSERT INTO pays (code, nom) VALUES('KNA','Saint-Kitts-et-Nevis'); 
INSERT INTO pays (code, nom) VALUES('SMR','Saint-Marin'); 
INSERT INTO pays (code, nom) VALUES('MAF','Saint-Martin (partie française)'); 
INSERT INTO pays (code, nom) VALUES('SXM','Saint-Martin (partie néerlandaise)'); 
INSERT INTO pays (code, nom) VALUES('SPM','Saint-Pierre-et-Miquelon'); 
INSERT INTO pays (code, nom) VALUES('VAT','Saint-Siège (Vatican)'); 
INSERT INTO pays (code, nom) VALUES('VCT','Saint-Vincent-et-les Grenadines'); 
INSERT INTO pays (code, nom) VALUES('SLV','Salvador'); 
INSERT INTO pays (code, nom) VALUES('WSM','Samoa'); 
INSERT INTO pays (code, nom) VALUES('ASM','Samoa américaines'); 
INSERT INTO pays (code, nom) VALUES('STP','Sao Tomé-et-Principe'); 
INSERT INTO pays (code, nom) VALUES('SEN','Sénégal'); 
INSERT INTO pays (code, nom) VALUES('SRB','Serbie'); 
INSERT INTO pays (code, nom) VALUES('SYC','Seychelles'); 
INSERT INTO pays (code, nom) VALUES('SLE','Sierra Leone'); 
INSERT INTO pays (code, nom) VALUES('SGP','Singapour'); 
INSERT INTO pays (code, nom) VALUES('SVK','Slovaquie'); 
INSERT INTO pays (code, nom) VALUES('SVN','Slovénie'); 
INSERT INTO pays (code, nom) VALUES('SOM','Somalie'); 
INSERT INTO pays (code, nom) VALUES('SDN','Soudan'); 
INSERT INTO pays (code, nom) VALUES('LKA','Sri Lanka'); 
INSERT INTO pays (code, nom) VALUES('SSD','Sud-Soudan'); 
INSERT INTO pays (code, nom) VALUES('SWE','Suède'); 
INSERT INTO pays (code, nom) VALUES('CHE','Suisse'); 
INSERT INTO pays (code, nom) VALUES('SUR','Suriname'); 
INSERT INTO pays (code, nom) VALUES('SJM','Svalbard et Jan Mayen'); 
INSERT INTO pays (code, nom) VALUES('SWZ','Swaziland'); 
INSERT INTO pays (code, nom) VALUES('SYR','Syrie'); 
INSERT INTO pays (code, nom) VALUES('TJK','Tadjikistan'); 
INSERT INTO pays (code, nom) VALUES('TWN','Taiwan'); 
INSERT INTO pays (code, nom) VALUES('TZA','Tanzanie'); 
INSERT INTO pays (code, nom) VALUES('TCD','Tchad'); 
INSERT INTO pays (code, nom) VALUES('ATF','Terres australes et antarctiques françaises'); 
INSERT INTO pays (code, nom) VALUES('IOT','Territoire britannique de l’Océan Indien'); 
INSERT INTO pays (code, nom) VALUES('THA','Thaïlande'); 
INSERT INTO pays (code, nom) VALUES('TLS','Timor-Leste'); 
INSERT INTO pays (code, nom) VALUES('TGO','Togo'); 
INSERT INTO pays (code, nom) VALUES('TKL','Tokelau'); 
INSERT INTO pays (code, nom) VALUES('TON','Tonga'); 
INSERT INTO pays (code, nom) VALUES('TTO','Trinité-et-Tobago'); 
INSERT INTO pays (code, nom) VALUES('TUN','Tunisie'); 
INSERT INTO pays (code, nom) VALUES('TKM','Turkménistan'); 
INSERT INTO pays (code, nom) VALUES('TUR','Turquie'); 
INSERT INTO pays (code, nom) VALUES('TUV','Tuvalu'); 
INSERT INTO pays (code, nom) VALUES('UKR','Ukraine'); 
INSERT INTO pays (code, nom) VALUES('URY','Uruguay'); 
INSERT INTO pays (code, nom) VALUES('VUT','Vanuatu'); 
INSERT INTO pays (code, nom) VALUES('VEN','Venezuela'); 
INSERT INTO pays (code, nom) VALUES('VNM','Viêt Nam'); 
INSERT INTO pays (code, nom) VALUES('WLF','Wallis-et-Futuna'); 
INSERT INTO pays (code, nom) VALUES('YEM','Yémen'); 
INSERT INTO pays (code, nom) VALUES('ZMB','Zambie'); 
INSERT INTO pays (code, nom) VALUES('ZWE','Zimbabwe'); 
